import crypto from 'crypto';
import { 
  auditLogs, 
  triggerGlobalLockdown, 
  logSecurityEvent,
  globalLockdownTime
} from '../services/securityService.js';
import nativeWorkerService from '../services/nativeWorkerService.js';

/**
 * Helper to compute ETags and match client header requests (304 Not Modified).
 */
const handleETag = (req, res, data) => {
  const jsonString = JSON.stringify(data);
  const hash = crypto.createHash('sha1').update(jsonString).digest('base64');
  const etag = `W/"${hash}"`;

  res.setHeader('ETag', etag);

  if (req.headers['if-none-match'] === etag) {
    return res.status(304).end();
  }

  return res.status(200).json(data);
};

/**
 * Fetch all cryptographic and RBAC audit logs.
 * GET /api/v1/security/audit-logs
 */
export const getAuditLogs = (req, res, next) => {
  try {
    return handleETag(req, res, {
      success: true,
      data: auditLogs
    });
  } catch (err) {
    next(err);
  }
};

/**
 * Fetch Web Application Firewall (WAF) traffic logs.
 * GET /api/v1/security/waf-stats
 */
export const getWafStats = (req, res, next) => {
  try {
    // Generate time points with baseline traffic and a distinct threats spike
    const wafData = [
      { label: '20:00', legitimate: 180, threats: 5 },
      { label: '20:05', legitimate: 220, threats: 8 },
      { label: '20:10', legitimate: 240, threats: 1402 }, // Major SQL injection scan spike
      { label: '20:15', legitimate: 200, threats: 12 },
      { label: '20:20', legitimate: 210, threats: 4 },
      { label: '20:25', legitimate: 190, threats: 6 },
      { label: '20:30', legitimate: 230, threats: 15 },
    ];

    return handleETag(req, res, {
      success: true,
      data: wafData
    });
  } catch (err) {
    next(err);
  }
};

/**
 * Triggers full-platform session revocation under Defcon Lockdown.
 * POST /api/v1/security/defcon
 */
export const triggerDefconLockdown = (req, res, next) => {
  try {
    const adminId = req.user.id;
    const adminEmail = req.user.email;

    // Hard-revoke sessions
    triggerGlobalLockdown(adminId);

    // Register in Immutable Audit Log
    const event = logSecurityEvent(
      'GLOBAL_SESSION_REVOCATION_EXECUTED',
      `Global Defcon lockdown initiated by administrator. All active JWT sessions revoked.`,
      {
        initiatedBy: adminId,
        email: adminEmail,
        lockdownTime: new Date().toISOString()
      },
      req
    );

    res.status(200).json({
      success: true,
      message: 'Global session revocation executed successfully.',
      data: {
        lockdownTime: globalLockdownTime,
        event
      }
    });
  } catch (err) {
    next(err);
  }
};

/**
 * Logs unauthorized access attempts (RBAC violations).
 * POST /api/v1/security/log-violation
 */
export const logRbacViolation = (req, res, next) => {
  try {
    // Zod schema has already validated the body payload
    const { path, userRole, userId, email } = req.body;

    const event = logSecurityEvent(
      'RBAC_VIOLATION_INTERCEPTED',
      `Unauthorized access attempt to resource pathway: ${path || 'unknown'}`,
      {
        attemptedPath: path,
        userRole: userRole || 'guest',
        userId: userId || 'anonymous',
        email: email || 'anonymous@vora.io'
      },
      req
    );

    res.status(201).json({
      success: true,
      message: 'RBAC violation successfully logged into forensic registry.',
      data: event
    });
  } catch (err) {
    next(err);
  }
};

/**
 * Simulates Master Key Pair generation for E2EE configuration using unmanaged native sandbox.
 * POST /api/v1/security/generate-key
 */
export const generateKeyPair = async (req, res, next) => {
  try {
    const adminId = req.user.id;
    const { algorithm = 'RSA-4096', keySize = 4096 } = req.body || {};
    
    // Invoke FFI key pair generation in sandboxed child process worker
    const keys = await nativeWorkerService.generateKeyPair(algorithm, keySize);
    
    // Compute key fingerprint hash from generated public key
    const publicKeyHash = crypto.createHash('sha256').update(keys.publicKey).digest('hex');
    const keyFingerprint = publicKeyHash.substring(0, 32).match(/.{2}/g).join(':');

    logSecurityEvent(
      'API_KEY_ROTATED',
      'Cryptographic master key pair regenerated by system administrator.',
      {
        actionInitiator: adminId,
        keyAlgorithm: algorithm,
        fingerprint: `sha256:${keyFingerprint}`
      },
      req
    );

    res.status(200).json({
      success: true,
      message: 'Cryptographic key pair successfully generated.',
      data: {
        publicKey: keys.publicKey,
        privateKey: keys.privateKey,
        fingerprint: `sha256:${keyFingerprint}`
      }
    });
  } catch (err) {
    next(err);
  }
};

/**
 * Verifies a cryptographic signature using FFI integration in isolated child process.
 * POST /api/v1/security/verify-signature
 */
export const verifySignature = async (req, res, next) => {
  try {
    const { signature, publicKey, msg } = req.body;
    
    const isValid = await nativeWorkerService.verifySignature(signature, publicKey, msg);

    logSecurityEvent(
      'SIGNATURE_VERIFIED',
      'Cryptographic signature verification processed via native sandboxed worker.',
      {
        result: isValid ? 'SUCCESS' : 'FAILED',
        signatureLength: signature ? signature.length : 0,
        publicKeyLength: publicKey ? publicKey.length : 0
      },
      req
    );

    res.status(200).json({
      success: true,
      message: isValid ? 'Signature is valid.' : 'Signature is invalid.',
      data: {
        isValid
      }
    });
  } catch (err) {
    next(err);
  }
};
