import crypto from 'crypto';
import { client, isRedisPassThrough } from '../config/redis.js';
import logger from './loggerService.js';

// In-memory global security configuration
export let globalLockdownTime = 0;
export let lockdownAdminId = null;

// Seed data for the Immutable Audit Logs
export const auditLogs = [
  {
    id: `evt-${crypto.randomUUID().split('-')[0]}`,
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(), // 5 mins ago
    action: 'MEMBER_ROLE_UPGRADED',
    description: 'User profile platform role changed from attendee to organizer.',
    ipAddress: '192.168.1.104',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)',
    payload: {
      targetUserId: 'c420f188-d113-40e1-a2c9-6c0b39678129',
      updatedBy: 'd3b07384-d113-40e1-a2c9-6c0b39678129',
      roleBefore: 'attendee',
      roleAfter: 'organizer'
    }
  },
  {
    id: `evt-${crypto.randomUUID().split('-')[0]}`,
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(), // 15 mins ago
    action: 'API_KEY_ROTATED',
    description: 'Cryptographic master key pair regenerated by system administrator.',
    ipAddress: '127.0.0.1',
    userAgent: 'PostmanRuntime/7.39.0',
    payload: {
      actionInitiator: 'd3b07384-d113-40e1-a2c9-6c0b39678129',
      keyAlgorithm: 'RSA-4096',
      fingerprint: 'sha256:4a:df:f3:12:9e:3a:41:88:bc:8a:1f:df'
    }
  },
  {
    id: `evt-${crypto.randomUUID().split('-')[0]}`,
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // 1 hour ago
    action: 'AUTHENTICATION_SUCCESS',
    description: 'User initiated a session from a recognized IP address.',
    ipAddress: '192.168.1.45',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    payload: {
      userId: 'd3b07384-d113-40e1-a2c9-6c0b39678129',
      email: 'organizer@vora.io',
      authMethod: 'PASSWORD_AND_MFA'
    }
  },
  {
    id: `evt-${crypto.randomUUID().split('-')[0]}`,
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), // 4 hours ago
    action: 'DATABASE_BACKUP_COMPLETED',
    description: 'Automated pg_dump database replication completed successfully.',
    ipAddress: '10.0.4.82',
    userAgent: 'VoraCronWorker/1.0.0',
    payload: {
      backupId: 'backup_replica_2026_06_13',
      fileSize: '42.8 MB',
      storageBucket: 'vora-backups-us-east'
    }
  },
  {
    id: `evt-${crypto.randomUUID().split('-')[0]}`,
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), // 24 hours ago
    action: 'SYSTEM_BOOT',
    description: 'Vora API core engine successfully instantiated.',
    ipAddress: '10.0.0.1',
    userAgent: 'VoraSystemEngine/2.1.0',
    payload: {
      nodeVersion: process.version,
      platform: process.platform,
      arch: process.arch
    }
  }
];

/**
 * Checks if a session has been terminated by global Defcon lockdown.
 * Revokes any token issued before lockdownTime, except for the admin who triggered it.
 */
export const verifyLockdown = (userId, iat) => {
  if (globalLockdownTime === 0) {
    return false;
  }
  
  const tokenIssuedAtMs = iat * 1000;
  
  if (tokenIssuedAtMs < globalLockdownTime) {
    // Revoked! Unless it is the admin's own session who triggered the lockdown
    return userId !== lockdownAdminId;
  }

  return false;
};

/**
 * Initiates the Automated Defcon Lockdown Protocol.
 */
export const triggerGlobalLockdown = (adminId) => {
  globalLockdownTime = Date.now();
  lockdownAdminId = adminId;
};

/**
 * Resets the Defcon lockdown status back to normal.
 */
export const resetGlobalLockdown = () => {
  globalLockdownTime = 0;
  lockdownAdminId = null;
};

/**
 * Appends a security event log entry to our in-memory audit ledger.
 */
export const logSecurityEvent = (action, description, payload = {}, req = null) => {
  const ipAddress = req ? getClientIp(req) : '127.0.0.1';
  const userAgent = req ? req.headers['user-agent'] || 'Unknown' : 'System Agent';

  const logEntry = {
    id: `evt-${crypto.randomUUID().split('-')[0]}`,
    timestamp: new Date().toISOString(),
    action,
    description,
    ipAddress,
    userAgent,
    payload
  };

  auditLogs.unshift(logEntry); // Insert at the top
  return logEntry;
};

/**
 * Helper to identify loopback and private sub-network ranges.
 */
export function isPrivateIp(ip) {
  if (!ip) return true;
  const cleanIp = ip.toLowerCase().trim();
  
  if (cleanIp === '::1' || cleanIp === 'localhost') return true;
  
  if (cleanIp.includes('.')) {
    if (cleanIp.startsWith('127.')) return true;
    if (cleanIp.startsWith('10.')) return true;
    if (cleanIp.startsWith('192.168.')) return true;
    if (cleanIp.startsWith('172.')) {
      const parts = cleanIp.split('.');
      if (parts.length >= 2) {
        const secondOctet = parseInt(parts[1], 10);
        if (secondOctet >= 16 && secondOctet <= 31) return true;
      }
    }
  }
  
  if (cleanIp.includes(':')) {
    if (cleanIp.startsWith('fe80:') || cleanIp.startsWith('fc00:') || cleanIp.startsWith('fd00:')) return true;
  }
  
  return false;
}

/**
 * Extracts the absolute leftmost non-private IP signature from the X-Forwarded-For proxy chain.
 */
export function getClientIp(req) {
  const xForwardedFor = req.headers['x-forwarded-for'];
  if (xForwardedFor) {
    const ips = xForwardedFor.split(',').map((ip) => ip.trim());
    for (const ip of ips) {
      if (ip && !isPrivateIp(ip)) {
        return ip;
      }
    }
    if (ips[0]) return ips[0];
  }
  return req.ip || req.socket.remoteAddress || '127.0.0.1';
}

/**
 * Evaluates real-time presence of client IP in blacklisted Redis sets.
 */
export async function isIpBlacklisted(ip) {
  if (isRedisPassThrough() || !client || !client.isOpen) {
    return false;
  }
  try {
    const isMember = await client.sIsMember('blacklist:ips', ip);
    if (!isMember) return false;

    const hasExpireKey = await client.exists(`blacklist:expire:${ip}`);
    if (!hasExpireKey) {
      await client.sRem('blacklist:ips', ip);
      return false;
    }
    return true;
  } catch (err) {
    logger.error({ module: 'securityService.js', ip, err: err.message }, 'Blacklist verification failed');
    return false;
  }
}

/**
 * Bans an offending IP by updating blacklist sets and writing 24h expiration keys.
 */
export async function banIp(ip) {
  if (isRedisPassThrough() || !client || !client.isOpen) {
    return false;
  }
  try {
    logger.warn({ module: 'securityService.js', ip }, 'INGRESS SHIELD: Quarantine IP for 24 hours');
    await client.multi()
      .sAdd('blacklist:ips', ip)
      .set(`blacklist:expire:${ip}`, '1', { EX: 24 * 60 * 60 })
      .exec();
    return true;
  } catch (err) {
    logger.error({ module: 'securityService.js', ip, err: err.message }, 'Failed to ban IP');
    return false;
  }
}

/**
 * Evaluates rate limiting breaches. Bans IP if multiple different profiles are breached within 10 minutes.
 */
export async function registerRateLimitBreach(ip, profileName) {
  if (isRedisPassThrough() || !client || !client.isOpen) {
    return;
  }
  const key = `breaches:${ip}`;
  const now = Date.now();
  const uniqueMember = `${profileName}:${crypto.randomUUID()}`;
  
  try {
    await client.multi()
      .zRemRangeByScore(key, '-inf', `(${now - 10 * 60 * 1000})`)
      .zAdd(key, { score: now, value: uniqueMember })
      .expire(key, 12 * 60)
      .exec();

    const breaches = await client.zRange(key, 0, -1);
    const profiles = new Set();
    
    for (const b of breaches) {
      const idx = b.indexOf(':');
      if (idx !== -1) {
        profiles.add(b.substring(0, idx));
      } else {
        profiles.add(b);
      }
    }

    if (profiles.size > 1) {
      await banIp(ip);
    }
  } catch (err) {
    logger.error({ module: 'securityService.js', ip, err: err.message }, 'Correlation check failed');
  }
}

/**
 * Ingress Interceptor Middleware: Drops blacklisted requests with empty 403 response before heavy V8 parsers start.
 */
export const blacklistInterceptor = async (req, res, next) => {
  const ip = getClientIp(req);
  const isBlocked = await isIpBlacklisted(ip);
  if (isBlocked) {
    res.setHeader('Connection', 'close');
    return res.status(403).end();
  }
  next();
};
